### ISSUE TITLE
Executing python scripts

### ISSUE THREAD

**Issue by TechWiz-3** [kgdn/pypost#2]
https://github.com/kgdn/pypost/blob/cc3b5d149713aa0c719350149cc2eac854704cf9/new_post.sh#L6

Just a note on the above, in case you didn't already know, you can put `#!/usr/bin/env python3` at the top of your python script to make it executable. Personally, I like to remove the `.py` at the end of the filename so I can just type `py_post` etc

**Comment by kgdn** [comment]
That worked! Thank you so much for the advice. I wouldn't have known otherwise!
This will be a massive help going forwards.
